# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# https://pip.pypa.io/en/stable/topics/caching/
cache:
  paths:
    - .cache/pip

before_script:
  - source /users/sarlab/tools/python/python-3.12.2-etad/bin/activate
  - which python ; python --version
  - which pip ; pip --version
  - python -m venv --upgrade-deps .venv
  - source .venv/bin/activate
  - which python ; python --version
  - which pip ; pip --version

default:
  tags:
    - veritas

pages:
  stage: deploy
  script:
  - pip install --upgrade .[docs]
  - cd docsrc
  - make html
  artifacts:
    paths:
    - _build/html/
  only:
  - pages
