name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      - develop

jobs:
  setup-conda:
    name: Set up Conda Environment
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v4
        with:
          environment-file: environment.yml
          miniforge-version: latest
          activate-environment: xvamp
          channel-priority: strict
          use-only-tar-bz2: true
          auto-activate-base: false

      - name: Test conda
        run: |
          conda env list
          which python
          python --version

  test:
    name: Run Tests
    needs: setup-conda
    runs-on: ubuntu-latest
    steps:
      - name: Activate environment
        uses: conda-incubator/setup-miniconda@v4
        with:
          activate-environment: xvamp

      - name: Install package in development mode
        run: |
          python -m pip install --no-deps --force-reinstall .

      - name: Run tests
        run: |
          python -m unittest -v

  build-docs:
    name: Build Documentation
    needs: setup-conda
    runs-on: ubuntu-latest
    container:
      image: condaforge/mambaforge:latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Activate environment
        uses: conda-incubator/setup-miniconda@v4
        with:
          activate-environment: xvamp

      - name: Install package with docs dependencies
        run: |
          python -m pip install --no-deps --force-reinstall .[docs]

      - name: Build documentation
        run: |
          cd docsrc
          sphinx-build -M html . _build
          mv _build/html ../public

      - name: Upload documentation artifacts
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: public/
          if-no-files-found: ignore
